name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      NPM_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/

    - name: npm install, build, test
      run: |
        npm i
        npm run build
        npm run test
        
    - name: deploy
      run: npx semantic-release
